ulcakeys:
  api_key: "your_apikey"
  uid: "your_uid"
  gen: "female"
  Authorization: "key"

ASR_config:
  nl_ServiceId : "ai4bharat/conformer-multilingual-indo_aryan-gpu--t4"
  en_ServiceId : "ai4bharat/whisper-medium-en--gpu--t4"
  hi_ServiceId : "ai4bharat/conformer-hi-gpu--t4"
  sl_ServiceId : "ai4bharat/conformer-multilingual-dravidian-gpu--t4"

MT_config : 
  mt_ServiceId : "ai4bharat/indictrans-v2-all-gpu--t4"

TTS_config :
  en_ServiceId : "ai4bharat/indic-tts-coqui-misc-gpu--t4"
  nl_ServiceId : "ai4bharat/indic-tts-coqui-indo_aryan-gpu--t4"
  sl_ServiceId : "ai4bharat/indic-tts-coqui-dravidian-gpu--t4"
